name: elixir-restful-api-on-aws

services:
  influxdb:
    image: influxdb:2
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: "admin"
      DOCKER_INFLUXDB_INIT_PASSWORD: "MyInitialAdminPassword"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "EEKpryGZk8pVDXmIuy484BKUxM5jOEDv7YNoeNZUbsNbpbPbP6kK_qY9Zsyw7zNnlZ7pHG16FYzNaqwLMBUz8g=="
      DOCKER_INFLUXDB_INIT_ORG: k6io
      DOCKER_INFLUXDB_INIT_BUCKET: demo
  grafana:
    image: grafana/grafana:12.1.4
    ports:
      - 3000:3000
    volumes:
      - ./_db/grafana:/var/lib/grafana
      - ./thirdparty/grafana:/etc/grafana/provisioning/
  k6:
    build: ./thirdparty/k6
    ports:
      - 6565:6565
    environment:
      - K6_OUT=xk6-influxdb=http://influxdb:8086
      - K6_INFLUXDB_ORGANIZATION=k6io
      - K6_INFLUXDB_BUCKET=demo
      - K6_INFLUXDB_INSECURE=true
      - K6_INFLUXDB_TOKEN=EEKpryGZk8pVDXmIuy484BKUxM5jOEDv7YNoeNZUbsNbpbPbP6kK_qY9Zsyw7zNnlZ7pHG16FYzNaqwLMBUz8g==
    volumes:
      - ./thirdparty/k6/samples:/scripts
